name: Crystal shard

on:
  push:
    branches:
      - "*"
jobs:
  build-test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      - uses: MeilCli/setup-crystal-action@v1
        with:
          crystal_version: 0.31.1
          shards_version: 0.9.0
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: shards install

      - name: Build
        run: crystal build src/cached_docker.cr --release --no-debug

      - name: Build
        run: ./cached_docker --version

      - name: Test
        run: crystal spec

      - uses: actions/upload-artifact@v1
        with:
          name: cached-docker-bin
          path: cached_docker
  deploy:
    runs-on: ubuntu-latest
    needs: build-test
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@master
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: devmasx/cached-docker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tagging: true
