name: Crystal shard

on:
  push:
    branches:
      - "*"
jobs:
  example:
    runs-on: ubuntu-16.04
    steps:
      - uses: MeilCli/setup-crystal-action@v1
        with:
          crystal_version: 0.31.1
          shards_version: 0.9.0
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install dependencies
        run: shards install
      - name: Build
        run: crystal build src/cached_docker.cr
      - name: Test
        run: crystal spec
