name: Crystal shard

on:
  push:
    branches:
      - "*"
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      - uses: MeilCli/setup-crystal-action@v1
        with:
          crystal_version: 0.31.1
          shards_version: 0.9.0
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: shards install

      - name: Test
        run: crystal spec

  build-alpine:
    # runs-on: ubuntu-16.04
    needs: test
    container:
      image: alpine:3.11.2
    steps:
      - uses: actions/checkout@master

      - name: Install system dependencies
        run: apk add libevent pcre libgcc crystal shards

      - name: Install dependencies
        run: shards install

      - name: Build
        run: crystal build src/cached_docker.cr --release --no-debug -o cached-docker

      - uses: actions/upload-artifact@v1
        with:
          name: cached-docker-alpine
          path: cached-docker
  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@master
      - name: Publish to DockerHub
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: devmasx/cached-docker
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tagging: true
