name: Crystal shard

on:
  push:
    branches:
      - "*"
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@master

      - uses: MeilCli/setup-crystal-action@v1
        with:
          crystal_version: 0.31.1
          shards_version: 0.9.0
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: shards install

      - name: Test
        run: crystal spec

  build-alpine:
    runs-on: ubuntu-16.04
    needs: test
    container:
      image: alpine:3.11.2
    steps:
      - uses: actions/checkout@master

      - name: Install system dependencies
        run: apk add libevent pcre libgcc musl-dev crystal shards

      - name: Install dependencies
        run: shards install

      - name: Build
        run: crystal build src/cached_docker.cr --release --static --no-debug -o cached-docker

      - uses: actions/upload-artifact@v1
        with:
          name: cached-docker-alpine
          path: cached-docker

  build-ubuntu:
    runs-on: ubuntu-16.04
    needs: test
    container:
      image: crystallang/crystal:0.32.1
    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: shards install

      - name: Build
        run: crystal build src/cached_docker.cr --release --static --no-debug -o cached-docker

      - uses: actions/upload-artifact@v1
        with:
          name: cached-docker-ubuntu
          path: cached-docker

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@master
      - name: Install crystal
        run: |
          xcode-select --switch /Library/Developer/CommandLineTools
          brew update
          brew install openssl
          brew install crystal

      - name: Install dependencies
        run: shards install

      - name: Build
        run: crystal build src/cached_docker.cr --release --static --no-debug -o cached-docker

      - uses: actions/upload-artifact@v1
        with:
          name: cached-docker-macos
          path: cached-docker

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build-alpine, build-ubuntu]
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@master
      - run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}
      - name: Publish to DockerHub
        uses: devmasx/cached-docker-build-push@v0.1.1
        with:
          image_name: devmasx/cached-docker
