name: Crystal shard

on:
  push:
    branches:
      - "*"
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-16.04
    container:
      image: crystallang/crystal:0.32.1

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: shards install

      - name: Test
        run: crystal spec

  build-ubuntu:
    runs-on: ubuntu-16.04
    needs: test
    container:
      image: crystallang/crystal:0.32.1

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: shards install

      - name: Build
        run: crystal build src/cached_docker.cr --release --static --no-debug -o releases/linux/cached-docker

      - uses: actions/upload-artifact@v1
        with:
          name: cached-docker-ubuntu
          path: releases/linux

      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        if: contains(github.ref, 'refs/tags/v')
        with:
          commit_message: Store linux release

  build-macos:
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Install crystal
        run: |
          brew update
          brew install libgc
          brew install gsl
          brew install openssl
          brew install crystal

      - name: Install dependencies
        run: shards install

      - name: Build
        run: crystal build src/cached_docker.cr -o releases/macos/cached-docker

      - uses: actions/upload-artifact@v1
        with:
          name: cached-docker-macos
          path: releases/macos

      - uses: stefanzweifel/git-auto-commit-action@v4.1.1
        if: contains(github.ref, 'refs/tags/v')
        with:
          commit_message: Store macOS release
