name: Crystal shard

on:
  push:
    branches:
      - "*"
    tags:
      - v*
jobs:
  test:
    runs-on: ubuntu-16.04
    container:
      image: crystallang/crystal:0.32.1

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: shards install

      - name: Test
        run: crystal spec

  build-ubuntu:
    runs-on: ubuntu-16.04
    needs: test
    container:
      image: crystallang/crystal:0.32.1

    steps:
      - uses: actions/checkout@master

      - name: Install dependencies
        run: shards install

      - name: Build
        run: crystal build src/cached_docker.cr --release --static --no-debug -o cached-docker

      - uses: actions/upload-artifact@v1
        with:
          name: cached-docker-ubuntu
          path: cached-docker

  build-macos:
    runs-on: macos-latest
    needs: test
    steps:
      - uses: actions/checkout@master
      - name: Install crystal
        run: |
          brew update
          brew install libgc
          brew install gsl
          brew install openssl
          brew install crystal

      - name: Install dependencies
        run: shards install

      - name: Build
        run: crystal build src/cached_docker.cr -o cached-docker

      - uses: actions/upload-artifact@v1
        with:
          name: cached-docker-macos
          path: cached-docker

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build-ubuntu]
    if: contains(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@master

      - name: Build
        run: crystal build src/cached_docker.cr --release --static --no-debug -o /bin/cached-docker

      - name: Docker login
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      - name: Publish to DockerHub
        run: |
          cached-docker -i devmasx/cached-docker -t $GITHUB_SHA
